### ISSUE TITLE
e importanta ordinea ifurilor aici... daca tu ai filtru pe toate, o sa faca doar dupa type.

### ISSUE THREAD

**Issue by stefanbulzan** [cezarhre/curs20.homework#2]
https://github.com/cezarhre/curs20.homework/blob/4dcae85058d6169b8085d48691c57fbf5556da3c/src/main/java/ro/fasttrackit/curs20/homework/budgetTransactions/service/TransactionService.java#L22

**Comment by cezarhre** [comment]
Am refacut ordinea
